### ISSUE TITLE
Nodes without 'labels' or 'properties' attributes cause exceptions. You can see my corresponding pull request for this.

### ISSUE THREAD

**Issue by Alan-R** [nigelsmall/py2neo#434]
Some nodes that come through this path don't have "labels" or "properties" attributes. I don't know why.

But this is almost the same code driving the new py2neo version - and it runs into this problem.

I do not yet create any nodes with labels, so that may be why you haven't seen this before. I'm not sure how the "properties" attribute normally gets set, but when I'm committing my changes created with a legacy.batch() operation, I run into these problems.

If you look at the pull request I made you can see how I worked around it.

**Comment by Alan-R** [comment]
Here's the traceback for the "properties" issue:
Traceback (most recent call last):
  File "./query.py", line 602, in <module>
    qstore.commit()
  File "/home/alanr/monitor/src/cma/store.py", line 999, in commit
    self._batch_construct_relate_nodes()        # These return new relationships
  File "/home/alanr/monitor/src/cma/store.py", line 877, in _batch_construct_relate_nodes
    print >> sys.stderr, ('==== Performing batch.create(%s): node relationships' % absrel)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/core.py", line 2475, in __str__
    return xstr(self.__unicode__())
  File "/usr/local/lib/python2.7/dist-packages/py2neo/core.py", line 2484, in __unicode__
    writer.write_relationship(self)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/cypher/lang.py", line 185, in write_relationship
    self.write_node(relationship.start_node)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/cypher/lang.py", line 154, in write_node
    if node.properties:
AttributeError: 'NodePointer' object has no attribute 'properties'

**Comment by Alan-R** [comment]
Here's the traceback for the 'labels' attribute problem. Note that this is the first one I fixed. Once I fixed it, then the second one (above) showed up. These nodes were created as part of a legacy.batch() operation.

Traceback (most recent call last):
  File "./query.py", line 602, in <module>
    qstore.commit()
  File "/home/alanr/monitor/src/cma/store.py", line 999, in commit
    self._batch_construct_relate_nodes()        # These return new relationships
  File "/home/alanr/monitor/src/cma/store.py", line 877, in _batch_construct_relate_nodes
    print >> sys.stderr, ('==== Performing batch.create(%s): node relationships' % absrel)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/core.py", line 2475, in __str__
    return xstr(self.__unicode__())
  File "/usr/local/lib/python2.7/dist-packages/py2neo/core.py", line 2484, in __unicode__
    writer.write_relationship(self)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/cypher/lang.py", line 184, in write_relationship
    self.write_node(relationship.start_node)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/cypher/lang.py", line 150, in write_node
    for label in sorted(node.labels):
AttributeError: 'NodePointer' object has no attribute 'labels'

**Comment by Alan-R** [comment]
Thanks Nigel!

On September 6, 2015 12:26:25 PM MDT, Nigel Small <notifications@github.com> wrote:
>Closed #434 via 02019f15c88ef3737750aa2485031936934c72b9.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/nigelsmall/py2neo/issues/434#event-402240634

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
