### ISSUE TITLE
crash with neo4j 3.0.0-M05

### ISSUE THREAD

**Issue by khafan246** [nigelsmall/py2neo#479]
updating to M05 version, crash happens in the first ```merge``` statement:
```
Traceback (most recent call last):
  File "/opt/src/py2neo/py2neo/packages/neo4j/v1/session.py", line 94, in session
    session = self.session_pool.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
  File "user.py", line 51, in user_from_entry
    graph.merge(user, "User", "username")
  File "/opt/src/py2neo/py2neo/database.py", line 618, in merge
    self.begin(autocommit=True).merge(walkable, label, *property_keys)
  File "/opt/src/py2neo/py2neo/database.py", line 368, in begin
    return self.transaction_class(self, autocommit)
  File "/opt/src/py2neo/py2neo/database.py", line 1422, in __init__
    self.session = driver.session()
  File "/opt/src/py2neo/py2neo/packages/neo4j/v1/session.py", line 96, in session
    session = Session(self)
  File "/opt/src/py2neo/py2neo/packages/neo4j/v1/session.py", line 428, in __init__
    self.connection = connect(driver.host, driver.port, **driver.config)
  File "/opt/src/py2neo/py2neo/packages/neo4j/v1/connection.py", line 367, in connect
    return Connection(s, **config)
  File "/opt/src/py2neo/py2neo/packages/neo4j/v1/connection.py", line 224, in __init__
    self.fetch()
  File "/opt/src/py2neo/py2neo/packages/neo4j/v1/connection.py", line 296, in fetch
    self.reset()
  File "/opt/src/py2neo/py2neo/packages/neo4j/v1/connection.py", line 260, in reset
    fetch()
  File "/opt/src/py2neo/py2neo/packages/neo4j/v1/connection.py", line 281, in fetch
    raw.writelines(self.channel.chunk_reader())
  File "/opt/src/py2neo/py2neo/packages/neo4j/v1/connection.py", line 166, in chunk_reader
    chunk_header = self._recv(2)
  File "/opt/src/py2neo/py2neo/packages/neo4j/v1/connection.py", line 149, in _recv
    raise ProtocolError("Server closed connection")
py2neo.packages.neo4j.v1.exceptions.ProtocolError: Server closed connection
```

**Comment by nigelsmall** [comment]
The v3 branch is not yet ready and will not stabilise until Neo4j 3.0 has been released.
